netbox/netbox/dcim/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from extras.views import ImageAttachmentEditView
from ipam.views import ServiceCreateView
from secrets.views import secret_add
from . import views
from .models import Device, Rack, Site

app_name = 'dcim'
urlpatterns = [

    # Regions
    url(r'^regions/$', views.RegionListView.as_view(), name='region_list'),
    url(r'^regions/add/$', views.RegionCreateView.as_view(), name='region_add'),
    url(r'^regions/import/$', views.RegionBulkImportView.as_view(), name='region_import'),
    url(r'^regions/delete/$', views.RegionBulkDeleteView.as_view(), name='region_bulk_delete'),
    url(r'^regions/(?P<pk>\d+)/edit/$', views.RegionEditView.as_view(), name='region_edit'),

    # Sites
    url(r'^sites/$', views.SiteListView.as_view(), name='site_list'),
    url(r'^sites/add/$', views.SiteCreateView.as_view(), name='site_add'),
    url(r'^sites/import/$', views.SiteBulkImportView.as_view(), name='site_import'),
    url(r'^sites/edit/$', views.SiteBulkEditView.as_view(), name='site_bulk_edit'),
    url(r'^sites/(?P<slug>[\w-]+)/$', views.SiteView.as_view(), name='site'),
    url(r'^sites/(?P<slug>[\w-]+)/edit/$', views.SiteEditView.as_view(), name='site_edit'),
    url(r'^sites/(?P<slug>[\w-]+)/delete/$', views.SiteDeleteView.as_view(), name='site_delete'),
    url(r'^sites/(?P<object_id>\d+)/images/add/$', ImageAttachmentEditView.as_view(), name='site_add_image', kwargs={'model': Site}),

    # Rack groups
    url(r'^rack-groups/$', views.RackGroupListView.as_view(), name='rackgroup_list'),
    url(r'^rack-groups/add/$', views.RackGroupCreateView.as_view(), name='rackgroup_add'),
    url(r'^rack-groups/import/$', views.RackGroupBulkImportView.as_view(), name='rackgroup_import'),
    url(r'^rack-groups/delete/$', views.RackGroupBulkDeleteView.as_view(), name='rackgroup_bulk_delete'),
    url(r'^rack-groups/(?P<pk>\d+)/edit/$', views.RackGroupEditView.as_view(), name='rackgroup_edit'),

    # Rack roles
    url(r'^rack-roles/$', views.RackRoleListView.as_view(), name='rackrole_list'),
    url(r'^rack-roles/add/$', views.RackRoleCreateView.as_view(), name='rackrole_add'),
    url(r'^rack-roles/import/$', views.RackRoleBulkImportView.as_view(), name='rackrole_import'),
    url(r'^rack-roles/delete/$', views.RackRoleBulkDeleteView.as_view(), name='rackrole_bulk_delete'),
    url(r'^rack-roles/(?P<pk>\d+)/edit/$', views.RackRoleEditView.as_view(), name='rackrole_edit'),

    # Rack reservations
    url(r'^rack-reservations/$', views.RackReservationListView.as_view(), name='rackreservation_list'),
    url(r'^rack-reservations/edit/$', views.RackReservationBulkEditView.as_view(), name='rackreservation_bulk_edit'),
    url(r'^rack-reservations/delete/$', views.RackReservationBulkDeleteView.as_view(), name='rackreservation_bulk_delete'),
    url(r'^rack-reservations/(?P<pk>\d+)/edit/$', views.RackReservationEditView.as_view(), name='rackreservation_edit'),
    url(r'^rack-reservations/(?P<pk>\d+)/delete/$', views.RackReservationDeleteView.as_view(), name='rackreservation_delete'),

    # Racks
    url(r'^racks/$', views.RackListView.as_view(), name='rack_list'),
    url(r'^rack-elevations/$', views.RackElevationListView.as_view(), name='rack_elevation_list'),
    url(r'^racks/add/$', views.RackEditView.as_view(), name='rack_add'),
    url(r'^racks/import/$', views.RackBulkImportView.as_view(), name='rack_import'),
    url(r'^racks/edit/$', views.RackBulkEditView.as_view(), name='rack_bulk_edit'),
    url(r'^racks/delete/$', views.RackBulkDeleteView.as_view(), name='rack_bulk_delete'),
    url(r'^racks/(?P<pk>\d+)/$', views.RackView.as_view(), name='rack'),
    url(r'^racks/(?P<pk>\d+)/edit/$', views.RackEditView.as_view(), name='rack_edit'),
    url(r'^racks/(?P<pk>\d+)/delete/$', views.RackDeleteView.as_view(), name='rack_delete'),
    url(r'^racks/(?P<rack>\d+)/reservations/add/$', views.RackReservationCreateView.as_view(), name='rack_add_reservation'),
    url(r'^racks/(?P<object_id>\d+)/images/add/$', ImageAttachmentEditView.as_view(), name='rack_add_image', kwargs={'model': Rack}),

    # Manufacturers
    url(r'^manufacturers/$', views.ManufacturerListView.as_view(), name='manufacturer_list'),
    url(r'^manufacturers/add/$', views.ManufacturerCreateView.as_view(), name='manufacturer_add'),
    url(r'^manufacturers/import/$', views.ManufacturerBulkImportView.as_view(), name='manufacturer_import'),
    url(r'^manufacturers/delete/$', views.ManufacturerBulkDeleteView.as_view(), name='manufacturer_bulk_delete'),
    url(r'^manufacturers/(?P<slug>[\w-]+)/edit/$', views.ManufacturerEditView.as_view(), name='manufacturer_edit'),

    # Device types
    url(r'^device-types/$', views.DeviceTypeListView.as_view(), name='devicetype_list'),
    url(r'^device-types/add/$', views.DeviceTypeCreateView.as_view(), name='devicetype_add'),
    url(r'^device-types/import/$', views.DeviceTypeBulkImportView.as_view(), name='devicetype_import'),
    url(r'^device-types/edit/$', views.DeviceTypeBulkEditView.as_view(), name='devicetype_bulk_edit'),
    url(r'^device-types/delete/$', views.DeviceTypeBulkDeleteView.as_view(), name='devicetype_bulk_delete'),
    url(r'^device-types/(?P<pk>\d+)/$', views.DeviceTypeView.as_view(), name='devicetype'),
    url(r'^device-types/(?P<pk>\d+)/edit/$', views.DeviceTypeEditView.as_view(), name='devicetype_edit'),
    url(r'^device-types/(?P<pk>\d+)/delete/$', views.DeviceTypeDeleteView.as_view(), name='devicetype_delete'),

    # Console port templates
    url(r'^device-types/(?P<pk>\d+)/console-ports/add/$', views.ConsolePortTemplateCreateView.as_view(), name='devicetype_add_consoleport'),
    url(r'^device-types/(?P<pk>\d+)/console-ports/delete/$', views.ConsolePortTemplateBulkDeleteView.as_view(), name='devicetype_delete_consoleport'),

    # Console server port templates
    url(r'^device-types/(?P<pk>\d+)/console-server-ports/add/$', views.ConsoleServerPortTemplateCreateView.as_view(), name='devicetype_add_consoleserverport'),
    url(r'^device-types/(?P<pk>\d+)/console-server-ports/delete/$', views.ConsoleServerPortTemplateBulkDeleteView.as_view(), name='devicetype_delete_consoleserverport'),

    # Power port templates
    url(r'^device-types/(?P<pk>\d+)/power-ports/add/$', views.PowerPortTemplateCreateView.as_view(), name='devicetype_add_powerport'),
    url(r'^device-types/(?P<pk>\d+)/power-ports/delete/$', views.PowerPortTemplateBulkDeleteView.as_view(), name='devicetype_delete_powerport'),

    # Power outlet templates
    url(r'^device-types/(?P<pk>\d+)/power-outlets/add/$', views.PowerOutletTemplateCreateView.as_view(), name='devicetype_add_poweroutlet'),
    url(r'^device-types/(?P<pk>\d+)/power-outlets/delete/$', views.PowerOutletTemplateBulkDeleteView.as_view(), name='devicetype_delete_poweroutlet'),

    # Interface templates
    url(r'^device-types/(?P<pk>\d+)/interfaces/add/$', views.InterfaceTemplateCreateView.as_view(), name='devicetype_add_interface'),
    url(r'^device-types/(?P<pk>\d+)/interfaces/edit/$', views.InterfaceTemplateBulkEditView.as_view(), name='devicetype_bulkedit_interface'),
    url(r'^device-types/(?P<pk>\d+)/interfaces/delete/$', views.InterfaceTemplateBulkDeleteView.as_view(), name='devicetype_delete_interface'),

    # Device bay templates
    url(r'^device-types/(?P<pk>\d+)/device-bays/add/$', views.DeviceBayTemplateCreateView.as_view(), name='devicetype_add_devicebay'),
    url(r'^device-types/(?P<pk>\d+)/device-bays/delete/$', views.DeviceBayTemplateBulkDeleteView.as_view(), name='devicetype_delete_devicebay'),

    # Device roles
    url(r'^device-roles/$', views.DeviceRoleListView.as_view(), name='devicerole_list'),
    url(r'^device-roles/add/$', views.DeviceRoleCreateView.as_view(), name='devicerole_add'),
    url(r'^device-roles/import/$', views.DeviceRoleBulkImportView.as_view(), name='devicerole_import'),
    url(r'^device-roles/delete/$', views.DeviceRoleBulkDeleteView.as_view(), name='devicerole_bulk_delete'),
    url(r'^device-roles/(?P<slug>[\w-]+)/edit/$', views.DeviceRoleEditView.as_view(), name='devicerole_edit'),

    # Platforms
    url(r'^platforms/$', views.PlatformListView.as_view(), name='platform_list'),
    url(r'^platforms/add/$', views.PlatformCreateView.as_view(), name='platform_add'),
    url(r'^platforms/import/$', views.PlatformBulkImportView.as_view(), name='platform_import'),
    url(r'^platforms/delete/$', views.PlatformBulkDeleteView.as_view(), name='platform_bulk_delete'),
    url(r'^platforms/(?P<slug>[\w-]+)/edit/$', views.PlatformEditView.as_view(), name='platform_edit'),

    # Devices
    url(r'^devices/$', views.DeviceListView.as_view(), name='device_list'),
    url(r'^devices/add/$', views.DeviceCreateView.as_view(), name='device_add'),
    url(r'^devices/import/$', views.DeviceBulkImportView.as_view(), name='device_import'),
    url(r'^devices/import/child-devices/$', views.ChildDeviceBulkImportView.as_view(), name='device_import_child'),
    url(r'^devices/edit/$', views.DeviceBulkEditView.as_view(), name='device_bulk_edit'),
    url(r'^devices/delete/$', views.DeviceBulkDeleteView.as_view(), name='device_bulk_delete'),
    url(r'^devices/(?P<pk>\d+)/$', views.DeviceView.as_view(), name='device'),
    url(r'^devices/(?P<pk>\d+)/edit/$', views.DeviceEditView.as_view(), name='device_edit'),
    url(r'^devices/(?P<pk>\d+)/delete/$', views.DeviceDeleteView.as_view(), name='device_delete'),
    url(r'^devices/(?P<pk>\d+)/inventory/$', views.DeviceInventoryView.as_view(), name='device_inventory'),
    url(r'^devices/(?P<pk>\d+)/status/$', views.DeviceStatusView.as_view(), name='device_status'),
    url(r'^devices/(?P<pk>\d+)/lldp-neighbors/$', views.DeviceLLDPNeighborsView.as_view(), name='device_lldp_neighbors'),
    url(r'^devices/(?P<pk>\d+)/config/$', views.DeviceConfigView.as_view(), name='device_config'),
    url(r'^devices/(?P<pk>\d+)/add-secret/$', secret_add, name='device_addsecret'),

netbox/netbox/netbox/urls.py
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.static import serve
from rest_framework_swagger.views import get_swagger_view

from netbox.views import APIRootView, HomeView, SearchView
from users.views import LoginView, LogoutView

swagger_view = get_swagger_view(title='NetBox API')

_patterns = [

    # Base views
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^search/$', SearchView.as_view(), name='search'),

    # Login/logout
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),

    # Apps
    url(r'^circuits/', include('circuits.urls')),
    url(r'^dcim/', include('dcim.urls')),
    url(r'^extras/', include('extras.urls')),
    url(r'^ipam/', include('ipam.urls')),
    url(r'^secrets/', include('secrets.urls')),
    url(r'^tenancy/', include('tenancy.urls')),
    url(r'^user/', include('users.urls')),
    url(r'^virtualization/', include('virtualization.urls')),

    # API
    url(r'^api/$', APIRootView.as_view(), name='api-root'),
    url(r'^api/circuits/', include('circuits.api.urls')),
    url(r'^api/dcim/', include('dcim.api.urls')),
    url(r'^api/extras/', include('extras.api.urls')),
    url(r'^api/ipam/', include('ipam.api.urls')),
    url(r'^api/secrets/', include('secrets.api.urls')),
    url(r'^api/tenancy/', include('tenancy.api.urls')),
    url(r'^api/virtualization/', include('virtualization.api.urls')),
    url(r'^api/docs/', swagger_view, name='api_docs'),

    # Serving static media in Django to pipe it through LoginRequiredMiddleware
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),

    # Admin
    url(r'^admin/', admin.site.urls),

]

if settings.DEBUG:
    import debug_toolbar
    _patterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

# Prepend BASE_PATH
urlpatterns = [
    url(r'^{}'.format(settings.BASE_PATH), include(_patterns))
]

netbox/netbox/users/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views

app_name = 'user'
urlpatterns = [

    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^password/$', views.ChangePasswordView.as_view(), name='change_password'),
    url(r'^api-tokens/$', views.TokenListView.as_view(), name='token_list'),
    url(r'^api-tokens/add/$', views.TokenEditView.as_view(), name='token_add'),
    url(r'^api-tokens/(?P<pk>\d+)/edit/$', views.TokenEditView.as_view(), name='token_edit'),
    url(r'^api-tokens/(?P<pk>\d+)/delete/$', views.TokenDeleteView.as_view(), name='token_delete'),
    url(r'^user-key/$', views.UserKeyView.as_view(), name='userkey'),
    url(r'^user-key/edit/$', views.UserKeyEditView.as_view(), name='userkey_edit'),
    url(r'^session-key/delete/$', views.SessionKeyDeleteView.as_view(), name='sessionkey_delete'),
    url(r'^recent-activity/$', views.RecentActivityView.as_view(), name='recent_activity'),

]

netbox/netbox/users/models.py
from __future__ import unicode_literals

import binascii
import os

from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator
from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Token(models.Model):
    """
    An API token used for user authentication. This extends the stock model to allow each user to have multiple tokens.
    It also supports setting an expiration time and toggling write ability.
    """
    user = models.ForeignKey(User, related_name='tokens', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    expires = models.DateTimeField(blank=True, null=True)
    key = models.CharField(max_length=40, unique=True, validators=[MinLengthValidator(40)])
    write_enabled = models.BooleanField(default=True, help_text="Permit create/update/delete operations using this key")
    description = models.CharField(max_length=100, blank=True)

    class Meta:
        default_permissions = []

    def __str__(self):
        # Only display the last 24 bits of the token to avoid accidental exposure.
        return "{} ({})".format(self.key[-6:], self.user)

    def save(self, *args, **kwargs):
        if not self.key:
            self.key = self.generate_key()
        return super(Token, self).save(*args, **kwargs)

    def generate_key(self):
        # Generate a random 160-bit key expressed in hexadecimal.
        return binascii.hexlify(os.urandom(20)).decode()

    @property
    def is_expired(self):
        if self.expires is None or timezone.now() < self.expires:
            return False
        return True

netbox/netbox/users/forms.py
from __future__ import unicode_literals

from django import forms
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm as DjangoPasswordChangeForm

from utilities.forms import BootstrapMixin
from .models import Token


class LoginForm(BootstrapMixin, AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['placeholder'] = ''
        self.fields['password'].widget.attrs['placeholder'] = ''


class PasswordChangeForm(BootstrapMixin, DjangoPasswordChangeForm):
    pass


class TokenForm(BootstrapMixin, forms.ModelForm):
    key = forms.CharField(required=False, help_text="If no key is provided, one will be generated automatically.")

    class Meta:
        model = Token
        fields = ['key', 'write_enabled', 'expires', 'description']
        help_texts = {
            'expires': 'YYYY-MM-DD [HH:MM:SS]'
        }

netbox/netbox/templates/users/_user.html
{% extends '_base.html' %}

{% block content %}
<div class="row">
    <div class="col-sm-12 col-md-8 col-md-offset-2">
        <h1>{% block title %}{% endblock %}</h1>
    </div>
</div>
<div class="row">
    <div class="col-sm-3 col-md-2 col-md-offset-2">
        <ul class="nav nav-pills nav-stacked">
            <li{% ifequal active_tab "profile" %} class="active"{% endifequal %}>
                <a href="{% url 'user:profile' %}">Profile</a>
            </li>
            <li{% ifequal active_tab "change_password" %} class="active"{% endifequal %}>
                <a href="{% url 'user:change_password' %}">Change Password</a>
            </li>
            <li{% ifequal active_tab "api_tokens" %} class="active"{% endifequal %}>
                <a href="{% url 'user:token_list' %}">API Tokens</a>
            </li>
            <li{% ifequal active_tab "userkey" %} class="active"{% endifequal %}>
                <a href="{% url 'user:userkey' %}">User Key</a>
            </li>
            <li{% ifequal active_tab "recent_activity" %} class="active"{% endifequal %}>
                <a href="{% url 'user:recent_activity' %}">Recent Activity</a>
            </li>
        </ul>
    </div>
	<div class="col-sm-9 col-md-6">
        {% block usercontent %}{% endblock %}
	</div>
</div>
{% endblock %}

netbox/netbox/templates/users/api_tokens.html
{% extends 'users/_user.html' %}
{% load helpers %}

{% block title %}API Tokens{% endblock %}

{% block usercontent %}
    <div class="row">
        <div class="col-md-12">
            {% for token in tokens %}
                <div class="panel panel-{% if token.is_expired %}danger{% else %}default{% endif %}">
                    <div class="panel-heading">
                        <div class="pull-right">
                            <a href="{% url 'user:token_edit' pk=token.pk %}" class="btn btn-xs btn-warning">Edit</a>
                            <a href="{% url 'user:token_delete' pk=token.pk %}" class="btn btn-xs btn-danger">Delete</a>
                        </div>
                        <i class="fa fa-key"></i> {{ token.key }}
                        {% if token.is_expired %}
                            <span class="label label-danger">Expired</span>
                        {% endif %}
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-4">
                                <span title="{{ token.created }}">{{ token.created|date }}</span><br />
                                <small class="text-muted">Created</small>
                            </div>
                            <div class="col-md-4">
                                {% if token.expires %}
                                    <span title="{{ token.expires }}">{{ token.expires|date }}</span><br />
                                {% else %}
                                    <span>Never</span><br />
                                {% endif %}
                                <small class="text-muted">Expires</small>
                            </div>
                            <div class="col-md-4">
                                {% if token.write_enabled %}
                                    <span class="label label-success">Enabled</span>
                                {% else %}
                                    <span class="label label-danger">Disabled</span>
                                {% endif %}<br />
                                <small class="text-muted">Create/edit/delete operations</small>
                            </div>
                        </div>
                        {% if token.description %}
                            <br /><span>{{ token.description }}</span>
                        {% endif %}
                    </div>
                </div>
            {% empty %}
                <p>You do not have any API tokens.</p>
            {% endfor %}
            <a href="{% url 'user:token_add' %}" class="btn btn-primary">
                <span class="fa fa-plus" aria-hidden="true"></span>
                Add a token
            </a>
        </div>
    </div>
{% endblock %}

netbox/netbox/templates/users/change_password.html
{% extends 'users/_user.html' %}
{% load form_helpers %}

{% block title %}Change Password{% endblock %}

{% block usercontent %}
    <form action="." method="post" class="form form-horizontal">
        {% csrf_token %}
        {% if form.non_field_errors %}
            <div class="panel panel-danger">
                <div class="panel-heading"><strong>Errors</strong></div>
                <div class="panel-body">
                    {{ form.non_field_errors }}
                </div>
            </div>
        {% endif %}
        <div class="panel panel-default">
            <div class="panel-heading"><strong>Password</strong></div>
            <div class="panel-body">
                {% render_field form.old_password %}
                {% render_field form.new_password1 %}
                {% render_field form.new_password2 %}
            </div>
        </div>
        <div class="text-right">
            <button type="submit" name="_update" class="btn btn-primary">Update</button>
            <a href="{% url 'user:profile' %}" class="btn btn-default">Cancel</a>
        </div>
    </form>
{% endblock %}

netbox/netbox/templates/users/profile.html
{% extends 'users/_user.html' %}
{% load helpers %}

{% block title %}User Profile{% endblock %}

{% block usercontent %}
    <small class="text-muted">User login</small>
    <h5>{{ request.user.username }}</h5>
    <small class="text-muted">Full name</small>
    <h5>{{ request.user.first_name }} {{ request.user.last_name }}</h5>
    <small class="text-muted">Email</small>
    <h5>{{ request.user.email }}</h5>
    <small class="text-muted">Registered</small>
    <h5>{{ request.user.date_joined }}</h5>
    <small class="text-muted">Groups</small>
    <h5>{{ request.user.groups.all|join:', ' }}</h5>
    <small class="text-muted">Admin access</small>
    <h5>{{ request.user.is_staff|yesno|capfirst }}</h5>
{% endblock %}

netbox/netbox/templates/users/recent_activity.html
{% extends 'users/_user.html' %}

{% block title %}Recent Activity{% endblock %}

{% block usercontent %}
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Time</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for action in recent_activity %}
                <tr>
                    <td>{{ action.time|date:'SHORT_DATETIME_FORMAT' }}</td>
                    <td>{{ action.icon }} {{ action.message|safe }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

netbox/netbox/templates/users/sessionkey_delete.html
{% extends 'utilities/obj_delete.html' %}

{% block message %}
    <p>Are you sure you want to delete your session key?</p>
{% endblock %}

netbox/netbox/templates/users/userkey.html
{% extends 'users/_user.html' %}

{% block title %}User Key{% endblock %}

{% block usercontent %}
    {% if userkey %}
        <div class="pull-right">
            <a href="{% url 'user:userkey_edit' %}" class="btn btn-warning">
                <span class="fa fa-pencil" aria-hidden="true"></span>
                Edit user key
            </a>
        </div>
        <h4>
            Your user key is:
            {% if userkey.is_active %}
                <span class="label label-success">Active</span>
            {% else %}
                <span class="label label-danger">Inactive</span>
            {% endif %}
        </h4>
        {% include 'inc/created_updated.html' with obj=userkey %}
        {% if not userkey.is_active %}
            <div class="alert alert-warning" role="alert">
                <i class="fa fa-warning"></i>
                Your user key is inactive. Ask an administrator to enable it for you.
            </div>
        {% endif %}
        <pre>{{ userkey.public_key }}</pre>
        <hr />
        {% if userkey.session_key %}
            <div class="pull-right">
                <a href="{% url 'user:sessionkey_delete' %}" class="btn btn-danger">
                    <span class="fa fa-trash" aria-hidden="true"></span>
                    Delete session key
                </a>
            </div>
            <h4>Session key: <span class="label label-success">Active</span></h4>
            <small class="text-muted">Created {{ userkey.session_key.created }}</small>
        {% else %}
            <h4>No active session key</h4>
        {% endif %}
    {% else %}
        <p>You don't have a user key on file.</p>
        <p>
            <a href="{% url 'user:userkey_edit' %}" class="btn btn-primary">
                <span class="fa fa-plus" aria-hidden="true"></span>
                Create a User Key
            </a>
        </p>
    {% endif %}
{% endblock %}

netbox/netbox/templates/users/userkey_edit.html
{% extends 'users/_user.html' %}
{% load static from staticfiles %}
{% load form_helpers %}

{% block title %}User Key{% endblock %}

{% block usercontent %}
    {% if userkey.is_active %}
        <div class="alert alert-danger" role="alert">
            <strong>Warning:</strong> Changing your public key will require your user key to be re-activated by another
            user. You will be unable to retrieve any secrets until your key has been reactivated.
        </div>
    {% endif %}
    <form action="." method="post" class="form">
        {% csrf_token %}
        <div class="form-group">
            {% render_field form.public_key %}
        </div>
        <div class="row">
            <div class="form-group">
                <div class="col-sm-6 col-md-6">
                    <button type="button" class="btn btn-info" id="generate_keypair">Generate a New Key Pair</button>
                </div>
                <div class="col-sm-6 col-md-6 text-right">
                    <button type="submit" name="_update" class="btn btn-primary">Save</button>
                    <a href="{% url 'user:userkey' %}" class="btn btn-default">Cancel</a>
                </div>
            </div>
        </div>
    </form>
    <div class="modal fade" id="new_keypair_modal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-md" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="new_keypair_modal_title">
                        New RSA Key Pair
                    </h4>
                </div>
                <div class="modal-body">
                    <strong>New Public Key</strong>
                    <div class="form-group">
                        <textarea class="form-control" id="new_pubkey" style="height: 250px;"></textarea>
                    </div>
                    <strong>New Private Key</strong>
                    <div class="form-group">
                        <textarea class="form-control" id="new_privkey" style="height: 250px;"></textarea>
                    </div>
                </div>
                <div class="modal-footer text-center">
                    <button type="button" class="btn btn-danger" id="use_new_pubkey" data-dismiss="modal">I have saved my new private key</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
<script src="{% static 'js/secrets.js' %}?v{{ settings.VERSION }}"></script>
{% endblock %}